Repository MemoriesOfTime/Nukkit-MOT, pull requests merged in 2023-08, with the labels that each got.

#13 Basic Support MinecartChest & MinecartHopper to tranfer items
  src/main/java/cn/nukkit/blockentity/BlockEntityHopper.java
  src/main/java/cn/nukkit/entity/item/EntityMinecartAbstract.java
  src/main/java/cn/nukkit/entity/item/EntityMinecartHopper.java
Labels: [Type] New Feature | 新特性

#20 Fixed placement of trapdoors and added new trapdoors
  src/main/java/cn/nukkit/block/Block.java
  src/main/java/cn/nukkit/block/BlockID.java
  src/main/java/cn/nukkit/block/BlockTrapdoor.java
  src/main/java/cn/nukkit/block/BlockTrapdoorAcacia.java
  src/main/java/cn/nukkit/block/BlockTrapdoorBirch.java
  src/main/java/cn/nukkit/block/BlockTrapdoorDarkOak.java
  src/main/java/cn/nukkit/block/BlockTrapdoorIron.java
  src/main/java/cn/nukkit/block/BlockTrapdoorJungle.java
  src/main/java/cn/nukkit/block/BlockTrapdoorSpruce.java
  src/main/java/cn/nukkit/math/BlockFace.java
Labels: [Type] New Feature | 新特性

#25 Fix Furnace Crafting and Add Experience Drops
  src/main/java/cn/nukkit/blockentity/BlockEntityFurnace.java
  src/main/java/cn/nukkit/event/inventory/FurnaceSmeltEvent.java
  src/main/java/cn/nukkit/inventory/CraftingManager.java
  src/main/java/cn/nukkit/inventory/FurnaceInventory.java
  src/main/java/cn/nukkit/inventory/transaction/action/SlotChangeAction.java
  src/main/resources/furnace_xp.json
Labels: [Type] bug | 漏洞, [Type] New Feature | 新特性

#26 Add Bubble Column
  src/main/java/cn/nukkit/block/Block.java
  src/main/java/cn/nukkit/block/BlockBubbleColumn.java
  src/main/java/cn/nukkit/block/BlockID.java
  src/main/java/cn/nukkit/block/BlockMagma.java
  src/main/java/cn/nukkit/block/BlockSoulSand.java
  src/main/java/cn/nukkit/entity/EntityLiving.java
  src/main/java/cn/nukkit/event/entity/EntityDamageEvent.java
Labels: [Type] New Feature | 新特性

#39 Update ItemBow.java
  src/main/java/cn/nukkit/item/ItemBow.java
Labels: [Type] bug | 漏洞

#30 Basic Sneak Enhancement
  src/main/java/cn/nukkit/Player.java
  src/main/java/cn/nukkit/entity/Entity.java
  src/main/java/cn/nukkit/entity/EntityHuman.java
  src/main/java/cn/nukkit/event/player/PlayerToggleCrawlEvent.java
  src/main/java/cn/nukkit/network/protocol/PlayerActionPacket.java
  src/main/java/cn/nukkit/network/protocol/StartGamePacket.java
Labels: [Type] New Feature | 新特性

#43 Add Crimson&Warped Signs
  src/main/java/cn/nukkit/block/Block.java
  src/main/java/cn/nukkit/block/BlockBubbleColumn.java
  src/main/java/cn/nukkit/block/BlockCrimsonSignPost.java
  src/main/java/cn/nukkit/block/BlockCrimsonWallSign.java
  src/main/java/cn/nukkit/block/BlockID.java
  src/main/java/cn/nukkit/block/BlockWarpedSignPost.java
  src/main/java/cn/nukkit/block/BlockWarpedWallSign.java
  src/main/java/cn/nukkit/item/Item.java
  src/main/java/cn/nukkit/item/ItemCrimsonSign.java
  src/main/java/cn/nukkit/item/ItemID.java
  src/main/java/cn/nukkit/item/ItemWarpedSign.java
Labels: [Type] New Feature | 新特性
